#!/usr/bin/env bash

write_install_report() {
    local deploy="$1" disk="$2" pubkey="$3"
    local report_dir report_file fingerprint model size serial

    report_dir="$deploy/etc/home-server"
    report_file="$report_dir/install-report.md"
    model="$(lsblk -dn -o MODEL "$disk" | sed 's/[[:space:]]*$//')"
    size="$(lsblk -dn -b -o SIZE "$disk")"
    serial="$(lsblk -dn -o SERIAL "$disk" | sed 's/[[:space:]]*$//')"
    fingerprint="$(ssh_key_fingerprint "$pubkey")"

    install -d -m 0755 "$report_dir"
    cat > "$report_file" <<EOF_REPORT
# Home Server Installation Report

Generated by Home Server Installer ${HSI_VERSION}.

## Image

- Moving reference: \`${IMAGE_REF}\`
- Resolved digest: \`${IMAGE_DIGEST}\`
- Variant: \`${IMAGE_VARIANT:-unspecified}\`
- Installer format: \`${INSTALLER_FORMAT_VERSION}\`

## Target disk

- Device: \`${disk}\`
- Model: ${model:-unknown}
- Serial: ${serial:-unknown}
- Size: $(human_bytes "$size")
- Partition policy: \`${PARTITION_POLICY}\`
- Root UUID: \`${HSI_ROOT_UUID}\`
- Boot UUID: \`${HSI_BOOT_UUID}\`

## SSH

- Public-key fingerprint: \`${fingerprint}\`
- Private key embedded: **no**

## Update policy

- Policy: \`${UPDATE_POLICY}\`
EOF_REPORT

    if [[ "$UPDATE_POLICY" == "home-server-stage-v1" ]]; then
        cat >> "$report_file" <<'EOF_REPORT'
- Zincati: masked
- rpm-ostreed automatic timer: enabled by local preset
- AutomaticUpdatePolicy: stage
EOF_REPORT
    else
        cat >> "$report_file" <<'EOF_REPORT'
- Image update policy preserved by installer
EOF_REPORT
    fi

    cat >> "$report_file" <<EOF_REPORT

## Result

- bootc deployment: completed
- bootc finalization: completed
- BLS UUID verification: passed
- SSH injection verification: passed
- installer temporary image storage: removed

This report contains no private SSH key material.
EOF_REPORT

    info "Installation report written to /etc/home-server/install-report.md on the installed system"
}
